# Generated by Django 2.0 on 2024-11-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Costume name')),#服装名
                ('sn', models.CharField(max_length=32, unique=True, verbose_name='Garment number')),#服装号
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),#价格
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=32, verbose_name='dimension')),#尺寸
                ('color', models.CharField(max_length=32, verbose_name='colour')),#颜色
                ('stock', models.PositiveIntegerField(verbose_name='inventory')),#库存
                ('desc', models.CharField(max_length=200, verbose_name='Description')),#描述
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),#创建时间
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),#修改时间
            ],
            options={
                'verbose_name': 'Clothing information',#服装信息
                'verbose_name_plural': 'Clothing information',#服装信息
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Client name')),#客户名
                ('phone', models.CharField(max_length=32, verbose_name='telephone')),#电话
                ('address', models.CharField(max_length=32, verbose_name='address')),#地址
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),#创建时间
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),#修改时间
            ],
            options={
                'verbose_name': 'Customer information',#客户信息
                'verbose_name_plural': 'Customer information',#客户信息
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Inorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Warehouse entry number')),#入库单号
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),#创建时间
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),#修改时间
            ],
            options={
                'verbose_name': 'Warehouse entry information',#入库单信息
                'verbose_name_plural': 'Warehouse entry information',#入库单信息
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='InorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Clothes', verbose_name='outfit')),#服装
                ('inorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Inorder', verbose_name='Warehouse warrant')),#入库单
            ],
            options={
                'verbose_name': 'Store entry details',#入库单详情
                'verbose_name_plural': 'Store entry details',#入库单详情
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Outorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='The invoice number')),#出库单号
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),#创建时间
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),#修改时间
            ],
            options={
                'verbose_name': 'Outbound information',#出库单信息
                'verbose_name_plural': 'Outbound information',#出库单信息
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='OutorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='quantity')),#数量
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Clothes', verbose_name='outfit')),#服装
                ('outorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Outorder', verbose_name='Outbound order')),#出库单
            ],
            options={
                'verbose_name': 'Details of the delivery slip',#出库单详情
                'verbose_name_plural': 'Details of the delivery slip',#出库单详情
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),#用户名
                ('password', models.CharField(max_length=100, verbose_name='cipher')),#密码
                ('name', models.CharField(max_length=32, verbose_name='name')),#姓名
                ('role', models.CharField(choices=[('operator', 'operator'), ('Administrator', 'Administrator')], default='操作员', max_length=32, verbose_name='Character')),#
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),#创建时间
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification Time')),#修改时间
            ],
            options={
                'verbose_name': 'User information',#用户信息
                'verbose_name_plural': 'User information',#用户信息
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='outorder',
            name='clothes',
            field=models.ManyToManyField(through='common.OutorderClothes', to='common.Clothes', verbose_name='outfit'),#服装
        ),
        migrations.AddField(
            model_name='outorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer', verbose_name='client'),#客户
        ),
        migrations.AddField(
            model_name='outorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='user'),#用户
        ),
        migrations.AddField(
            model_name='inorder',
            name='clothes',
            field=models.ManyToManyField(through='common.InorderClothes', to='common.Clothes', verbose_name='outfit'),#服装
        ),
        migrations.AddField(
            model_name='inorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer', verbose_name='client'),#客户
        ),
        migrations.AddField(
            model_name='inorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='user'),#用户
        ),
    ]
