# Generated by Django 2.0 on 2024-11-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Costume name')),
                ('sn', models.CharField(max_length=32, unique=True, verbose_name='Garment number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=32, verbose_name='dimension')),
                ('color', models.CharField(max_length=32, verbose_name='colour')),
                ('stock', models.PositiveIntegerField(verbose_name='inventory')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'Clothing information',
                'verbose_name_plural': 'Clothing information',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Client name')),
                ('phone', models.CharField(max_length=32, verbose_name='telephone')),
                ('address', models.CharField(max_length=32, verbose_name='address')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'Customer information',
                'verbose_name_plural': 'Customer information',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Inorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Warehouse entry number')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'Warehouse entry information',
                'verbose_name_plural': 'Warehouse entry information',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='InorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Clothes', verbose_name='outfit')),
                ('inorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Inorder', verbose_name='Warehouse warrant')),
            ],
            options={
                'verbose_name': 'Store entry details',
                'verbose_name_plural': 'Store entry details',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Outorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='The invoice number')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification time')),
            ],
            options={
                'verbose_name': 'Outbound information',
                'verbose_name_plural': 'Outbound information',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='OutorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='quantity')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Clothes', verbose_name='outfit')),
                ('outorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Outorder', verbose_name='Outbound order')),
            ],
            options={
                'verbose_name': 'Details of the delivery slip',
                'verbose_name_plural': 'Details of the delivery slip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='cipher')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('role', models.CharField(choices=[('operator', 'operator'), ('Administrator', 'Administrator')], default='operator', max_length=32, verbose_name='Character')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modification Time')),
            ],
            options={
                'verbose_name': 'User information',
                'verbose_name_plural': 'User information',
                'ordering': ['create_time'],
            },
        ),
        migrations.AddField(
            model_name='outorder',
            name='clothes',
            field=models.ManyToManyField(through='common.OutorderClothes', to='common.Clothes', verbose_name='outfit'),
        ),
        migrations.AddField(
            model_name='outorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='outorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='inorder',
            name='clothes',
            field=models.ManyToManyField(through='common.InorderClothes', to='common.Clothes', verbose_name='outfit'),
        ),
        migrations.AddField(
            model_name='inorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Customer', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='inorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User', verbose_name='user'),
        ),
    ]
